### ISSUE TITLE
Tests: common debug function

### ISSUE THREAD

**Issue by RDIL** [RDIL/area4#131]
# Feature request

## Idea
like a debug(“hello world”) func so we don’t have to type out the whole thing in test-code.py

This would end up printing “[DEBUG] hello world”
## Context
Hard to type out

## Helpfulness
Makes it easy

**Comment by RDIL** [comment]
@N8python this is quite easy.  Want to take a shot at it?

**Comment by N8python** [comment]
I will tommorow

**Comment by RDIL** [comment]
I'll do it now.
