### ISSUE TITLE
Need contributing guidelines!   

### ISSUE THREAD

**Issue by RDIL** [RDIL/area4#16]
If anybody wants to get an extra PR for Hacktoberfest, I would love if somebody could write some simple contributing guidelines for the project!  It doesn't have to contain anything special, just the normal 'be nice', 'follow the code of conduct', etc.  It most likely won't take more than 5 minutes and would help us out a lot 👍 :D

**Comment by danieldeveloper001** [comment]
@RDIL, and @kritokrator, what do you think of this template that I already use in my own projects? There are gitmoji suggestions included :)

https://github.com/danieldeveloper001/scaffolder/blob/master/CONTRIBUTING.md

**Comment by kritokrator** [comment]
@danieldeveloper001 wow this one is much better than what I whipped up

**Comment by RDIL** [comment]
Going to add one part from yours @danieldeveloper001!  Thanks :)

**Comment by danieldeveloper001** [comment]
@RDIL, glad it was helpful :wink:
