### ISSUE TITLE
Random number dividers

### ISSUE THREAD

**Issue by RDIL** [RDIL/area4#29]
Could somebody please make a divider (number 35) that uses Python’s random library and is a different random number every time?  This counts twards Hacktoberfest!

**Comment by kurokochin** [comment]
So the divider number 35 will generate random number as a text for the divider (ex: 1283173571920381028312)?

**Comment by RDIL** [comment]
@kurokochin yup!

**Comment by kurokochin** [comment]
I'll work on it!

**Comment by RDIL** [comment]
Alright thanks :D

**Comment by RDIL** [comment]
Merged!
