### ISSUE TITLE
Poll: function change (breaking)

### ISSUE THREAD

**Issue by RDIL** [RDIL/area4#3]
Right now, running the functions just print the existing variable to the console.  Do you guys think we should keep it as-is, or use the ```return``` option?

**Comment by dylanfw** [comment]
I think it would be better for the functions to return strings instead of printing directly to the console so that users could use the dividers more flexibly, for example:

`foo = f"First line\n{area4.div1()}\nSecond line"`

I've created PR #5 in case you decide to do this.
