### ISSUE TITLE
Alphabet dividers

### ISSUE THREAD

**Issue by RDIL** [RDIL/area4#38]
Hello everyone, 
want an extra PR for Hacktoberfest?  You have come to the right place!  

We need dividers for each letter of the alphabet.  Here are the requirements:
* [X] Need a divider for every letter of the alphabet
* [X] 12 of that letter per divider
* [X] Dividers need to be numbered along with existing ones

Important: make sure to open a pull request on the alphabet_divs branch, not master!  

Thanks and happy Hacktoberfest!

**Comment by brtln** [comment]
I can work on this. Would you like to have capitalized and lowercased letters?

**Comment by RDIL** [comment]
WIP: Fixed by #39
