### ISSUE TITLE
Repository open to Hacktoberfest!  

### ISSUE THREAD

**Issue by RDIL** [RDIL/area4#4]
Just so everyone knows, this repository is open to all PRs for Hacktoberfest!

**Comment by BallisticZer0** [comment]
What could i do for this, and what do you want me to do?

**Comment by RDIL** [comment]
🤷‍♂️ whatever you feel would be helpful/useful!

**Comment by BallisticZer0** [comment]
So i could make a python game/ script?

**Comment by BallisticZer0** [comment]
And where would you want the files that make?

**Comment by AshwatKumar** [comment]
I want to contribute , how can I help ?!

**Comment by RDIL** [comment]
@AshwatKumar if you could write simple contributing guidelines that would be amazing!

**Comment by rbidanta** [comment]
Let me know of any open issue that I can help fixing?

**Comment by CoffeeGoddess** [comment]
@rbidanta check #20

**Comment by RDIL** [comment]
@rbidanta @AshwatKumar see #34

**Comment by RDIL** [comment]
Very little time left!  Make sure to get your last PRs in :]

**Comment by RDIL** [comment]
We’re now done!  Thank you all new contributors!! :]
