### ISSUE TITLE
Emoji dividers

### ISSUE THREAD

**Issue by RDIL** [RDIL/area4#40]
Hey everybody,
Want an extra PR for Hacktoberfest?  Here is the perfect solution for you!  We need emoji dividers (common emojis such as the smiley face and sad face).  *We need anywhere from 1 to ten of them.*  Feel free to open a pull request if you feel you can do so.  (Writing documentation for these new dividers is optional!)

**Comment by anmol-dhingra** [comment]
Working on this.

**Comment by RDIL** [comment]
Alright 👍

**Comment by amrutha3** [comment]
Can I add new emojis to this list? You've mentioned only 92

**Comment by amrutha3** [comment]
Can I add new emoji dividers other than the 92 you've mentioned?

**Comment by RDIL** [comment]
Oh well never mind my last message
