### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by water900** [RDIL/area4#50]
One function to get dividers

**Comment by RDIL** [comment]
Hmm, that could be an interesting future addition.

**Comment by RDIL** [comment]
I'll ask for some help from our other collaborators later.

**Comment by RDIL** [comment]
We are trying to get a prototype out for this, but we may need to rewrite some systems to do so.

**Comment by RDIL** [comment]
To be included in rewrite.

**Comment by RDIL** [comment]
Done in rewrite!
