### ISSUE TITLE
Add count of divider elements.

### ISSUE THREAD

**Issue by Athul-CA** [RDIL/area4#84]
## Idea  
Add count as  a parameter to be assigned by the user for showing  the number of divider elements to be shown.

## Context  
Got this by seeing the potential of dividers in python

## Helpfulness  
More flexibility and openness to the code

**Comment by RDIL** [comment]
Would this be for the make-div function or in general?

**Comment by Athul-CA** [comment]
Yes

**Comment by Athul-CA** [comment]
This can be an optional parameter and there should be a default one for the count

**Comment by RDIL** [comment]
What I’ll do is I’ll add it to make-div and put it in the individual
functions sometime in the future.

**Comment by RDIL** [comment]
It has been added to the `make-div` function.  Will be added to the rewrite later.

**Comment by Athul-CA** [comment]
Cool

Kind Regards,
       Athul Cyriac Ajay

**Comment by RDIL** [comment]
For a temporary rewrite solution, we need to port ninexball's make-div function to rewrite

**Comment by RDIL** [comment]
@CoffeeGoddess can you port ninexball's make-div function?

**Comment by RDIL** [comment]
#99

**Comment by RDIL** [comment]
Done!   Thanks for the suggestion :)
